language: node_js

node_js:
- "lts/*"

notifications:
  email: false

before_install:
- npm install

install:
- npm run bootstrap

script:
- npm run build
- npm run test:coveralls

cache:
  directories:
  - "node_modules"
