language: node_js
sudo: required
dist: trusty
services: docker

node_js:
- "lts/*"

notifications:
  email: false

before_install:
- npm i -g lerna@2.11.x
- lerna clean --yes

install:
- echo install

script:
- echo build

after_success:
- echo "Cheking TRAVIS_EVENT_TYPE is cron -> TRAVIS_EVENT_TYPE = $TRAVIS_EVENT_TYPE"
- test $TRAVIS_EVENT_TYPE = "cron" && BUILD_TAG="4.0.$TRAVIS_BUILD_NUMBER-nightly" && echo "Generate new BUILD_TAG = $BUILD_TAG"

before_deploy:
- TRAVIS_TAG=$BUILD_TAG
- echo Generated Releases for BUILD_TAG = $BUILD_TAG

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  prerelease: true
  name: $BUILD_TAG
  body: This release is an early preview of the new Bot Framework Emulator. Please consider it to be experimental, and we'd love to hear your feedback.
  on:
    branch: v4
    condition: $BUILD_TAG

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
